name = "Havoc Realms S4"
author = "minecraftbossdj"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76c969b38b734cff2603e40ae64f618b0b66688dccb55d48a6525ec06364fbf1"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
