name = "Havoc Realms S4"
author = "minecraftbossdj"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c47b78e4ad40e3d9e2923bc35ff192c2ff272896950d549505c01d936e757b3"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
